FROM python:3.10

COPY requirements.txt /app/requirements.txt
WORKDIR /app

# dependencies 
RUN pip install -r requirements.txt
RUN pip install gunicorn

ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

ENV PORT 8080

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0app:app